# Create Array 
np.array()


In [1]:
import numpy as np
a = np.array([1,2,3,4,5], dtype = "int16")
print(a)
b = np.array([[1, 2, 3, 4], [3, 2, 1, 5],[1, 2, 3, 6]])
print(b)

[1 2 3 4 5]
[[1 2 3 4]
 [3 2 1 5]
 [1 2 3 6]]


# Get Dimension (a.ndim)

In [2]:
print(a.ndim)
print(b.ndim)

1
2


# Get Shape (a.shape)

In [14]:
print(a.shape)
print(b.shape)

(5,)
(3, 4)


In [ ]:
# Get type (a.dtype)

print(a.dtype)
print(b.dtype)

# Can change type by using dtype = "int16"

int16
int64


In [22]:
# Get itemSize (a.itemsize)
print(b.itemsize)

# Get Size (a.size)
print(b.size)

# Get Total_Size (a.nbytes) = a.size * a.itemsize
print(b.nbytes)

8
12
96


In [ ]:
# Get a Specific Element [r, c]
print(b[0,1])
print(b[-1,-1])

# Get a specific row [r, :]
print(b[0, :])

# Get a specific column [:, c]
print(b[:, 0])

# Step size [row/column, starting index: Ending index: StepSize]
print(b[0,  0:: 2]) # For row
print(b[:, 0:2:1]) # For Column

2
6
[1 2 3 4]
[1 3 1]
[1 3]
[[1 2]
 [3 2]
 [1 2]]


In [ ]:
# Create a Data set of any numbers -> np.full(shape, number, dtype)
x = np.full((2,3,4), 100, dtype = "int")

# Create a Data set of any numbers _like -> np.full_like(array, number)
np.full_like(x, 101)



array([[[101, 101, 101, 101],
        [101, 101, 101, 101],
        [101, 101, 101, 101]],

       [[101, 101, 101, 101],
        [101, 101, 101, 101],
        [101, 101, 101, 101]]])

In [20]:
# Create a Data set of Ones -> np.ones((shape), dtype)
y = np.ones((2,2,3), dtype = "int")
print(y)

# Create a Data set of Zeros -> np.zeros((shape), dtype)
np.zeros((y.shape), dtype = "int")

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [54]:
# Create the Data set of any random decimal numbers -> np.random.rand(shape)
np.random.rand(3,2,4)

# Create the Data set of any random decimal number of defined _sample -> np.random.random_sample(array.shape)
np.random.random_sample(x.shape)

array([[[0.75909602, 0.00525511, 0.0104851 , 0.34749713],
        [0.57569164, 0.83394618, 0.37464032, 0.76147106],
        [0.70707917, 0.10396812, 0.62366431, 0.41568052]],

       [[0.18562802, 0.19047171, 0.15805194, 0.64730172],
        [0.64742063, 0.49662557, 0.37634068, 0.08747551],
        [0.55822455, 0.92092822, 0.17905556, 0.04012948]]])

In [58]:
# Create the Data set of any integer -> np.random.randint(start_value, end_value, size = (x,y..)
np.random.randint(10, 1000, size=(2,3,2))

array([[[ 34,  36],
        [142, 157],
        [ 28, 979]],

       [[131,  82],
        [191, 234],
        [557, 537]]])

In [23]:
# Identity Matrix -> np.identity(shape)
identity_array = np.identity(4)
print(identity_array)

# Another way identity matrix-> np.eye(shape)
iden_array = np.eye(4)
print(iden_array)
print(type(iden_array))



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
<class 'numpy.ndarray'>


In [25]:
# Repeat an Array -> np.repeat(array, number, axis=0\1)
arr = np.array([[1,2,3,4]])
r = np.repeat(arr,5, axis=0)
print(r)

s = np.repeat(arr,5, axis=1)
print(s)

# Arange -> np.arange(number)
c = np.arange(16)
print(c)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [26]:
# Reshape -> Array.reshape((shape))
d = c.reshape((4,4))
print(d)

# Flatten -> Array.flatten()
e = d.flatten()
print("\n",e)
# It gives copy

# Ravel -> Array.ravel() 
f = c.ravel()
print(f)
# It gives original view

#Transpose -> Array.T
d.T

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [4]:
# List as Numpy Array -> np.asarray(list)
List = [1,2,3,4,5,6]
print(type(List))
np_array = np.asarray(List)
print(np_array)
print(type(np_array))

<class 'list'>
[1 2 3 4 5 6]
<class 'numpy.ndarray'>
