In [2]:
import numpy as np

# Sorting -> array.sort() or np.sort(array)

a = np.array([1,5,7,3,2,0])
a.sort()
print(a)

# Sorting 2D Array -> np.sort(array, Axis = 0\1)
# Axis = 0 -> Columns are Sorted
# Axis = 1 -> Rows are Sorted
b = np.array([[1,9,3,11,5], [2,6,8,9,7], [3,4,5,6,7], [9,8,7,6,4]])
np.sort(b, axis = 0)

[0 1 2 3 5 7]


array([[ 1,  4,  3,  6,  4],
       [ 2,  6,  5,  6,  5],
       [ 3,  8,  7,  9,  7],
       [ 9,  9,  8, 11,  7]])

In [3]:
# Filtering

e = np.arange(21)
print(e)
f = e[e % 2 == 0]     # array[Mask]
print(f)

# Mask Condition
Mask = e > 9
g = e[Mask]
print(g)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20]
[10 11 12 13 14 15 16 17 18 19 20]


In [7]:
# Fancy Indexing

num = np.arange(8)
index = [0,2,5] 
print(num[index])

# Where 
num2 = np.where(num>4)
print(num2)
print(num[num2])


[0, 2, 5]
[0 2 5]
(array([5, 6, 7]),)
[5 6 7]


In [6]:
# Conditions -> np.where(Main Condition, If true do this, If false do this)
num3 = np.where(num>5, num*10, "False")
print(num)
print(num3)

[0 1 2 3 4 5 6 7]
['False' 'False' 'False' 'False' 'False' 'False' '60' '70']


In [ ]:
# Concatenate -> np.concatenate((array1, array2))
a1 = np.arange(4)
a2 = np.arange(3)
a3 = np.concatenate((a1, a2))
print(a3)

# Compatibility Check -> array1.shape == array2.shape
b1 = np.array([1,2,3])
b2 = np.array([5,6,7])
print(b1.shape==b2.shape)

[0 1 2 3 0 1 2]
True


In [8]:
# Adding new Row -> np.vstack((array, new_row)) 
# (vstack - vertical stack), (hstack - Horizontal stack)
arr1 = np.array([[1,2], [2,3]])
new_row = np.array([6,7])
arr2 = np.vstack((arr1, new_row))
print(f"The array with new row is: \n{arr2}")


The array with new row is: 
[[1 2]
 [2 3]
 [6 7]]


In [10]:
# Adding new Column -> np.hstack((array, new_col)) 
new_col = np.array([[6], [7]])
arr3 = np.hstack((arr1, new_col))
print(f"The array with new col is: \n{arr3}")

# Deleting -> np.delete(Array, indx)
arr_2 = arr2.flatten()
print(f"The flattened array is: {arr_2}")


The array with new col is: 
[[1 2 6]
 [2 3 7]]
The flattened array is: [1 2 2 3 6 7]


In [11]:
delete1 = np.delete(arr_2, 5)
print(f"The value after delete is:\n{delete1}")


# Slice object -> np.s_[start:stop:step]
deleted1= np.delete(arr_2, np.s_[0:-1:2])
print(f"The deleted value is:\n{deleted1}")

The value after delete is:
[1 2 2 3 6]
The deleted value is:
[2 3 7]


In [12]:
# Create Array of evenly spaced Value. (you need) -> np.linspace(start_value, end_value, Total values you need between them)
abc = np.linspace(0,10,5)
print(abc)

# Create Array of evenly spaced Value. -> np.arange(start_value, end_value, Step Value)
bcd = np.arange(0,11,5)
print(bcd)

[ 0.   2.5  5.   7.5 10. ]
[ 0  5 10]


In [14]:
# Array Maths

a = np.random.randint(10,20,(3,3))
b = np.random.randint(20,30,(3,3))
print(a)
print(b)

[[12 11 15]
 [17 13 19]
 [12 18 14]]
[[20 25 21]
 [26 24 27]
 [27 22 26]]


In [16]:
print("sum is:\n", a+b)
print("diff is:\n", a-b)
print("mul is:\n", a*b)
print("div is:\n", a/b)

sum is:
 [[32 36 36]
 [43 37 46]
 [39 40 40]]
diff is:
 [[ -8 -14  -6]
 [ -9 -11  -8]
 [-15  -4 -12]]
mul is:
 [[240 275 315]
 [442 312 513]
 [324 396 364]]
div is:
 [[0.6        0.44       0.71428571]
 [0.65384615 0.54166667 0.7037037 ]
 [0.44444444 0.81818182 0.53846154]]


In [17]:
# Another method
print("sum is:\n", np.add(a, b))
print("diff is:\n", np.subtract(a, b))
print("mul is:\n", np.multiply(a, b))
print("div is:\n", np.divide(a, b))

sum is:
 [[32 36 36]
 [43 37 46]
 [39 40 40]]
diff is:
 [[ -8 -14  -6]
 [ -9 -11  -8]
 [-15  -4 -12]]
mul is:
 [[240 275 315]
 [442 312 513]
 [324 396 364]]
div is:
 [[0.6        0.44       0.71428571]
 [0.65384615 0.54166667 0.7037037 ]
 [0.44444444 0.81818182 0.53846154]]
