In [7]:
import numpy as np

# Sorting -> array.sort() or np.sort(array)

a = np.array([1,5,7,3,2,0])
a.sort()
print(a)

# Sorting 2D Array -> np.sort(array, Axis = 0\1)
# Axis = 0 -> Columns are Sorted
# Axis = 1 -> Rows are Sorted
b = np.array([[1,9,3,11,5], [2,6,8,9,7], [3,4,5,6,7], [9,8,7,6,4]])
np.sort(b, axis = 0)

[0 1 2 3 5 7]


array([[ 1,  4,  3,  6,  4],
       [ 2,  6,  5,  6,  5],
       [ 3,  8,  7,  9,  7],
       [ 9,  9,  8, 11,  7]])

In [16]:
# Filtering

e = np.arange(21)
f = e[e % 2 == 0]     # array[Mask]
print(f)

# Mask Condition
Mask = e > 9
g = e[Mask]
print(g)


[ 0  2  4  6  8 10 12 14 16 18 20]
[10 11 12 13 14 15 16 17 18 19 20]


In [25]:
# Fancy Indexing

num = np.arange(8)
index = [0,2,5] 
print(num[index])

# Where 
num2 = np.where(num>4)
print(num2)
print(num[num2])

# Conditions -> np.where(Main Condition, If true do this, If false do this)
num3 = np.where(num>5, num*10, "False")
print(num)
print(num3)

[0 2 5]
(array([5, 6, 7]),)
[5 6 7]
[0 1 2 3 4 5 6 7]
['False' 'False' 'False' 'False' 'False' 'False' '60' '70']


In [ ]:
# Concatenate -> np.concatenate((array1, array2))
a1 = np.arange(4)
a2 = np.arange(3)
a3 = np.concatenate((a1, a2))
print(a3)

# Compatibility Check -> array1.shape == array2.shape
b1 = np.array([1,2,3])
b2 = np.array([5,6,7])
print(b1.shape==b2.shape)

[0 1 2 3 0 1 2]
True


In [60]:
# Adding new Row -> np.vstack((array, new_row)) 
# (vstack - vertical stack), (hstack - Horizontal stack)
arr1 = np.array([[1,2], [2,3]])
new_row = np.array([6,7])
arr2 = np.vstack((arr1, new_row))
print(f"The array with new row is: \n{arr2}")

# Adding new Column -> np.hstack((array, new_row)) 
new_col = np.array([[6], [7]])
arr3 = np.hstack((arr1, new_col))
print(f"The array with new col is: \n{arr3}")

# Deleting -> np.delete(Array, indx)
arr_2 = arr2.flatten()
print(f"The flattened array is: {arr_2}")
delete1 = np.delete(arr_2, 5)
print(f"The value after delete is:\n{delete1}")


# Slice object -> np.s_[start:stop:step]
deleted1= np.delete(arr_2, np.s_[0:-1:2])
print(f"The deleted value is:\n{deleted1}")


The array with new row is: 
[[1 2]
 [2 3]
 [6 7]]
The array with new col is: 
[[1 2 6]
 [2 3 7]]
The flattened array is: [1 2 2 3 6 7]
The value after delete is:
[1 2 2 3 6]
The deleted value is:
[2 3 7]
